root_ldir: '/tmp'
root_fdir: '/'

ftp_host: ftp.rma.usda.gov
ftp_user: anonymous
ftp_pass: 'jacksparrow@gmail.com'

excluded_files:
- mysql.tar.gz

excluded_dirs:
- MAPS
- Applications
- Policies
- References
- pub
