root_ldir: /tmp/ftptest/
root_fdir: MISC

ftp_host: ftp.microsoft.com
ftp_user: anonymous
ftp_pass: 'nobody@knows.com'

excluded_files:
- mysql.tar.gz

excluded_dirs:
- beckyk
- csformat
- DAILYKB
- FDC
- FULLKB
- Homenet
- Jeffreyf
- KB
- KBSPV
- Markesh
- Peach
- Store
- STORE1
- test
